name: Domain Portfolio
favicon: null
layout_spectrum: 0.6931477333419025
typography_spectrum: 0.571956837316975
title: Domain Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.36247491813264787
  lightness: 0.537144053960219
  saturation: 0.7319837382528931
  rhythmicContrast: 0.7358135178219527
purpose: []
